In [68]:
import pandas as pd
import os
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import string
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

In [53]:
dset = pd.read_csv(r"C:\Subbu\Personal\Data Science\Code Practice\New\DataSciencewithPractical-main\Test_05_15\Cellphone.csv")
dset.head(8)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   
6           1821     0          1.7         0   4       1          10    0.8   
7           1954     0          0.5         1   0       0          24    0.8   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   
5        164        1  ...       1004      1654  1067    17     1         10   
6        139        8  ...        381      1018  3220    13     8         18   
7        187        4  ...        512      1149   700    16     3          5   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  
5        1             0     0            1  
6        1             0     1            3  
7        1             1     1            0  

[8 rows x 21 columns]

In [54]:
dinfo=dset.info()
print(dinfo)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [55]:
dset.describe()

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [56]:
dset['price_range'].value_counts()

1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

In [57]:
dset.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [58]:
X = dset[['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range']].values
X[0:5]

array([[8.420e+02, 0.000e+00, 2.200e+00, 0.000e+00, 1.000e+00, 0.000e+00,
        7.000e+00, 6.000e-01, 1.880e+02, 2.000e+00, 2.000e+00, 2.000e+01,
        7.560e+02, 2.549e+03, 9.000e+00, 7.000e+00, 1.900e+01, 0.000e+00,
        0.000e+00, 1.000e+00, 1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, 1.000e+00, 0.000e+00, 1.000e+00,
        5.300e+01, 7.000e-01, 1.360e+02, 3.000e+00, 6.000e+00, 9.050e+02,
        1.988e+03, 2.631e+03, 1.700e+01, 3.000e+00, 7.000e+00, 1.000e+00,
        1.000e+00, 0.000e+00, 2.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, 1.000e+00, 2.000e+00, 1.000e+00,
        4.100e+01, 9.000e-01, 1.450e+02, 5.000e+00, 6.000e+00, 1.263e+03,
        1.716e+03, 2.603e+03, 1.100e+01, 2.000e+00, 9.000e+00, 1.000e+00,
        1.000e+00, 0.000e+00, 2.000e+00],
       [6.150e+02, 1.000e+00, 2.500e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+01, 8.000e-01, 1.310e+02, 6.000e+00, 9.000e+00, 1.216e+03,
        1.786e+03, 2.769e+03, 1.600e+01, 8.000e+00, 1.100e+0

In [59]:
y = dset['price_range'].values
y[0:5]

array([1, 2, 2, 2, 1], dtype=int64)

In [75]:
X = preprocessing.StandardScaler().fit_transform(X)
X[0:5]

array([[-0.90259726, -0.9900495 ,  0.83077942, -1.01918398, -0.76249466,
        -1.04396559, -1.38064353,  0.34073951,  1.34924881, -1.10197128,
        -1.3057501 , -1.40894856, -1.14678403,  0.39170341, -0.78498329,
         0.2831028 ,  1.46249332, -1.78686097, -1.00601811,  0.98609664,
        -0.4472136 ],
       [-0.49513857,  1.0100505 , -1.2530642 ,  0.98117712, -0.99289039,
         0.95788598,  1.15502422,  0.68754816, -0.12005944, -0.66476784,
        -0.64598879,  0.58577791,  1.70446468,  0.46731702,  1.11426556,
        -0.63531667, -0.73426721,  0.55964063,  0.99401789, -1.01409939,
         0.4472136 ],
       [-1.5376865 ,  1.0100505 , -1.2530642 ,  0.98117712, -0.53209893,
         0.95788598,  0.49354568,  1.38116548,  0.13424391,  0.20963905,
        -0.64598879,  1.39268422,  1.07496821,  0.44149774, -0.31017108,
        -0.86492153, -0.36814045,  0.55964063,  0.99401789, -1.01409939,
         0.4472136 ],
       [-1.41931861,  1.0100505 ,  1.19851653, -1.01918398

In [76]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (1600, 21) (1600,)
Test set: (400, 21) (400,)


In [78]:
X_train

array([[ 0.3971732 , -0.9900495 , -1.13048516, ...,  0.99401789,
        -1.01409939, -1.34164079],
       [-1.10518845,  1.0100505 , -1.2530642 , ..., -1.00601811,
        -1.01409939,  1.34164079],
       [ 1.69239105, -0.9900495 , -0.51758998, ...,  0.99401789,
         0.98609664,  1.34164079],
       ...,
       [ 0.52464631, -0.9900495 ,  0.70820038, ...,  0.99401789,
        -1.01409939, -1.34164079],
       [-1.60369936, -0.9900495 , -1.2530642 , ..., -1.00601811,
        -1.01409939,  1.34164079],
       [ 1.55808903, -0.9900495 , -0.64016902, ..., -1.00601811,
         0.98609664,  0.4472136 ]])

In [62]:
#test_x = dset.drop(columns=['price_range'],axis=1)
#test_y = dset['price_range']

In [79]:
model = GaussianNB()

In [80]:
y_train = y_train.astype('int')

In [92]:
model.fit(X_train,y_train)

GaussianNB()

In [93]:
type(X_test)

numpy.ndarray

In [94]:
y_pred = model.predict(X_test)

In [95]:
len(y_test), len(y_pred)

(400, 400)

In [96]:
acc_score = accuracy_score(y_test, y_pred)

In [97]:
print('The accuracy of the NB model is :', acc_score)

The accuracy of the NB model is : 1.0


In [100]:
predict_train = model.predict(X_train)
print('Target on train data',predict_train) 

Target on train data [0 3 3 ... 0 3 2]


In [102]:
accuracy_train = accuracy_score(y_train,predict_train)
print('accuracy_score on train dataset : ', accuracy_train)

accuracy_score on train dataset :  1.0


In [103]:
predict_test = model.predict(X_test)
print('Target on test data',predict_test) 

Target on test data [3 0 2 0 2 1 3 1 3 3 3 3 1 0 3 0 1 3 2 2 2 0 3 3 3 0 0 0 3 0 1 3 3 2 1 2 0
 3 3 3 2 3 0 1 1 2 0 3 1 3 3 0 1 1 1 0 3 3 3 1 0 1 1 2 2 0 3 2 2 0 0 0 0 1
 0 3 2 1 1 3 0 0 3 1 1 3 1 1 1 0 1 0 2 1 3 2 0 1 1 3 1 1 2 2 1 2 1 3 3 0 1
 3 1 3 2 0 2 1 1 3 3 3 2 0 3 3 3 1 0 0 3 2 1 0 2 1 0 2 3 0 3 1 1 1 1 2 3 3
 2 2 1 0 3 0 1 0 2 0 0 1 1 0 2 2 3 0 1 1 3 3 0 2 0 1 0 0 0 3 2 2 2 2 2 0 0
 3 2 3 2 2 0 3 0 2 0 2 1 3 2 0 0 0 3 1 3 3 2 3 1 3 1 2 0 1 2 3 0 1 0 1 1 1
 0 1 0 3 2 3 2 0 1 1 0 2 0 0 1 2 1 0 3 3 2 2 2 1 3 0 2 0 0 0 0 3 0 3 1 3 1
 2 2 3 1 0 2 0 3 1 0 0 2 1 1 1 3 1 1 2 2 0 3 1 2 0 1 1 3 3 3 2 3 3 3 2 3 2
 3 2 1 0 2 0 1 1 3 3 3 1 3 1 0 1 2 1 2 1 1 1 1 2 3 0 3 1 2 2 0 3 3 1 3 0 1
 2 0 2 3 3 1 3 1 0 0 2 2 0 3 3 0 3 2 0 0 2 0 0 2 2 0 1 0 3 1 1 1 3 3 1 1 0
 0 3 3 1 2 2 0 0 0 3 3 0 3 0 0 2 2 2 2 1 0 0 0 1 3 3 0 2 2 0]


In [104]:
accuracy_test = accuracy_score(y_test,predict_test)
print('accuracy_score on test dataset : ', accuracy_test)

accuracy_score on test dataset :  1.0
