In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
%matplotlib inline

In [4]:
df = pd.read_csv(r'C:\Subbu\Personal\Data Science\Code Practice\New\DataSciencewithPractical-main\Test_05_15\fraud-detection.csv')
df.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  
0  M1979787155             0.0             0.0        0  
1  M2044282225             0.0             0.0        0  
2   C553264065             0.0             0.0        1  
3    C38997010         21182.0             0.0        1  
4  M1230701703             0.0             0.0        0

In [5]:
df['isFraud'].value_counts()

0    100049
1       116
Name: isFraud, dtype: int64

In [6]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud'],
      dtype='object')

In [19]:
X = df[['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
       'oldbalanceDest', 'newbalanceDest', 'isFraud']].values  #.astype(float)
X[0:5]

array([[1.0000000e+00, 9.8396400e+03, 1.7013600e+05, 1.6029636e+05,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.8642800e+03, 2.1249000e+04, 1.9384720e+04,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.8100000e+02, 1.8100000e+02, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.8100000e+02, 1.8100000e+02, 0.0000000e+00,
        2.1182000e+04, 0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.1668140e+04, 4.1554000e+04, 2.9885860e+04,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00]])

In [20]:
y = df['isFraud'].values
y[0:5]

array([0, 0, 1, 1, 0], dtype=int64)

In [21]:
X = preprocessing.StandardScaler().fit_transform(X)
X[0:5]

array([[-4.11064284, -0.47578063, -0.2653281 , -0.27125245, -0.36675544,
        -0.42274735, -0.03405043],
       [-4.11064284, -0.49894534, -0.3209643 , -0.32316856, -0.36675544,
        -0.42274735, -0.03405043],
       [-4.11064284, -0.50383448, -0.32883701, -0.33031047, -0.36675544,
        -0.42274735, 29.36820354],
       [-4.11064284, -0.50383448, -0.32883701, -0.33031047, -0.35793833,
        -0.42274735, 29.36820354],
       [-4.11064284, -0.47046969, -0.31337672, -0.31929962, -0.36675544,
        -0.42274735, -0.03405043]])

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=0)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (80132, 7) (80132,)
Test set: (20033, 7) (20033,)


In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
k = 5

#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier()

In [33]:
yhat = neigh.predict(X_test)
yhat[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [34]:
np.unique(yhat)

array([0, 1], dtype=int64)

In [35]:
from sklearn import metrics

print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  1.0
Test set Accuracy:  1.0


In [36]:
metrics.confusion_matrix(y_train, neigh.predict(X_train))

array([[80043,     0],
       [    0,    89]], dtype=int64)

In [37]:
metrics.confusion_matrix(y_test, yhat)

array([[20006,     0],
       [    0,    27]], dtype=int64)